services:
  - type: web
    name: pixel2parcel-backend
    env: python
    rootDir: Pixel2Parcel_v2/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
